### ISSUE TITLE
GetEmailCampaign : no statistics

### ISSUE THREAD

**Issue by rflorent** [sendinblue/APIv3-php-library#27]
Hello,

The object \SendinBlue\Client\Model\GetEmailCampaign returned by the api call getEmailCampaign() at [https://github.com/sendinblue/APIv3-php-library/blob/master/lib/Api/EmailCampaignsApi.php#L380](url) , doesn't contain the _statistics_ property as it is showed in the api docs : https://developers.sendinblue.com/v3.0/reference#getemailcampaign-1

It's a big problem, we can't retrieve statistics for one campaign.

Thanks

**Comment by ekta-slit** [comment]
Hi @rflorent 
Thanks for reporting the issue, we will improve & update our PHP Api Client soon.

**Comment by florianproxi** [comment]
@rflorent no solution actually to bypass this ?

**Comment by florianproxi** [comment]
Up @ekta-slit !

**Comment by florianproxi** [comment]
Where are you @ekta-slit ?

**Comment by ekta-slit** [comment]
Hi @rflorent 

Thanks for reporting the issue, it has been fixed, including the `recipients` field as well with `statistics`.
Please switch to the latest release.

Thanks

**Comment by florianproxi** [comment]
Hi @ekta-slit sorry but I just tested and I still do not have statistics via the GetEmailCampaign method ...

**Comment by ekta-slit** [comment]
@florianproxi Please raise a support ticket here https://account.sendinblue.com/support sharing your complete code.

Thanks
